### ISSUE TITLE
Is there only the windows  version

### ISSUE THREAD

**Issue by xxkafu** [ocminer/suprminer#10]
Is there only the windows version ? How can I compile on Linux (Ubuntu) ?

Thx

**Comment by ocminer** [comment]
compiling @ linux: 

git clone https://github.com/ocminer/suprminer
cd suprminer
sh autogen.sh
./configure
make 

that's basically all - it depends on build-essential, libcurl4-openssl-dev and a few other dependencies, check the README.md
