### ISSUE TITLE
hasrates for different algos

### ISSUE THREAD

**Issue by lyolyalya** [ocminer/suprminer#3]
Hello,can you share somewhere in readme or something typical hashrates for some cards?
1060,1070,1080ti?cause you are saying about optimizations everyday and i can't realize - what algo is improved in a new version.thanks

**Comment by ocminer** [comment]
Unlike other miners, all algos are improved on this miner .. I don't have the time to test all the algos but you can run some benchmarks and report back when you have time.

**Comment by lyolyalya** [comment]
ok.i already benchmarking your miner but results are very innacurate.can i increase benchmarking time for all algos somehow?

**Comment by ocminer** [comment]
When you run it with -a x16r --benchmark for example you can run it as long as you like

**Comment by lyolyalya** [comment]
yes.but if you say that all algos are improving time after time it's interesting to bench them all at once.
is  "-N, --statsavg        number of samples used to display hashrate (default: 30)" can help?
