### ISSUE TITLE
Unstable 1.5.7 Restart issue

### ISSUE THREAD

**Issue by jugi1** [ocminer/suprminer#5]
Latest version suprminer-1.5.7
is not stable and it made my computer restart several times and miner stoping.

Using 1070ti.

PS
I did not have that issues in previous versions

**Comment by platinum4** [comment]
Clear overclocks

**Comment by ocminer** [comment]
That's possible because it's using more resources of your gpu. Also power usage should be a bit higher with the latest version.

**Comment by jugi1** [comment]
You should NOTE when doing this changes.

What Afterburner settings you propose ?

**Comment by ocminer** [comment]
i don't use afterburner at all, i'm running linux
