### ISSUE TITLE
x16rt not working on ZergPool 

### ISSUE THREAD

**Issue by UselessGuru** [ocminer/suprminer#5]
Your miner does not seem to work with some pools. Is that not worth investigating???
Other miners, e.g. SRBMiner work on the same pool (ZergPool).

Miner just sits idle.

Command line used:

`ccminer.exe -a x16rt -o stratum+tcp://x16rt.mine.zergpool.com:3696 -u ***************************`

Windows 10 x64 1809, Nvidia 481.18 drivers, GTX1080Ti

**Comment by ocminer** [comment]
x16rt in this miner is for VEIL - not for clones as GIN

**Comment by UselessGuru** [comment]
Thank you. I did not see this mentioned in a readme.
