### ISSUE TITLE
Improve other algos in the future?

### ISSUE THREAD

**Issue by fdoving** [ocminer/suprminer#6]
Hey nice work on this. Works very well.

Will you improve other algos in the future?
(Like x17 is alot faster on alexis 1.0 in my experience, as an example).

I'm dreaming of "the one and only ccminer for all algos"

**Comment by ocminer** [comment]
Yes, absolutely working on that :)

**Comment by fdoving** [comment]
Nice, and +10 for the issue-respons-time ;)
