### ISSUE TITLE
Thanks for the miner!

### ISSUE THREAD

**Issue by TheMeasles** [ocminer/suprminer#9]
Everything works fine on Ubuntu 16.04

Not seeing the advertised speed increases, though. I get perhaps 5-8% better hash rate between version 1.0 and 1.5 for x16r

Am I doing/reading something wrong?

**Comment by ocminer** [comment]
All good, x16r is an algo dependant algo... sometimes you're hashing more Keccak, sometimes more cubehash and sometimes more sha512 - my optimizations are (yet) only for a few kernels. The more use of those kernel is made, the more speedup you have. 

Other coins, like x11, nist5 etc see a better overall improvement.
